DATASET:
  root_dataset: "./data/"
  list_train: "./data/metal_training.odgt"
  list_val: "./data/metal_validation.odgt"
  num_class: 2
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 300 # this might cause problem
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 5
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True # the result will be saved in .png
  checkpoint: "epoch_1.pth"

TEST:
  checkpoint: "epoch_1.pth"
  result: "./"

DIR: "ckpt/ade20k-resnet50dilated-ppm_deepsup"
